name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (SDL2)
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev

    - name: Verify SDL2
      run: |
        sdl2-config --version
        sdl2-config --cflags
        sdl2-config --libs

    - name: Build
      run: |
        make

    - name: Clean
      run: |
        make clean
